name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-api-gateway:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      working-directory: ./api-gateway
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with coverage
      working-directory: ./api-gateway
      run: |
        pytest --cov=app --cov-report=xml --cov-report=term-missing -v
    
    - name: Check coverage threshold
      working-directory: ./api-gateway
      run: |
        coverage report --fail-under=80
  
  build-api-gateway:
    needs: test-api-gateway
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      working-directory: ./api-gateway
      run: |
        docker build -t lighthouse/api-gateway:latest .
    
    - name: Test Docker image
      run: |
        docker run -d -p 8000:8000 --name test-api lighthouse/api-gateway:latest
        sleep 5
        curl -f http://localhost:8000/health || exit 1
        docker stop test-api

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install linting tools
      run: |
        pip install flake8 black
    
    - name: Run flake8
      run: |
        flake8 api-gateway/app --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 api-gateway/app --count --max-complexity=10 --max-line-length=100 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check api-gateway/app
